repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: local
  hooks:
    - id: lint
      name: Running Linters
      entry: make lint
    
    - id: format
      name: Running code formatters
      entry: make format
    
    - id: unit-tests
      name: Running unit tests.
      entry: make tests-unit
